import { applyProductionModifier, applyUpgradeCostModifier, getCharacter } from './characters'

export interface DistilleryTier {
  name: string
  baseOutput: number   // units of alcohol produced per season
  heatPerSeason: number
  cost: number         // purchase/upgrade cost in dollars
}

export interface Distillery {
  id: number
  playerId: number
  cityId: number
  tier: number         // 1-5
  stillNumber: number  // 1-3
  purchasePrice: number
}

export const DISTILLERY_TIERS: Record<number, DistilleryTier> = {
  1: { name: 'Stills (Moonshine base)', baseOutput: 4, heatPerSeason: 1, cost: 200 },
  2: { name: 'Filters & Barrels',       baseOutput: 8, heatPerSeason: 2, cost: 500 },
  3: { name: 'Aging Tanks',             baseOutput: 14, heatPerSeason: 4, cost: 1000 },
  4: { name: 'Botanical Infusers',      baseOutput: 22, heatPerSeason: 7, cost: 2000 },
  5: { name: 'Master Distillery',       baseOutput: 34, heatPerSeason: 12, cost: 4000 }
}

export function getBaseOutput(tier: number): number {
  return DISTILLERY_TIERS[tier]?.baseOutput ?? 0
}

/**
 * Cost to upgrade to targetTier (or purchase first still at tier 1).
 * Returns 0 if targetTier is out of range.
 */
export function getUpgradeCost(targetTier: number, characterClass: string): number {
  const tier = DISTILLERY_TIERS[targetTier]
  if (!tier) return 0
  return Math.floor(applyUpgradeCostModifier(characterClass, tier.cost))
}

/** Sell a still at 50% of its purchase price */
export function getSellPrice(purchasePrice: number): number {
  return Math.floor(purchasePrice * 0.5)
}

/** True if the player can add another still (max 3) */
export function canAddStill(playerStills: Distillery[]): boolean {
  return playerStills.length < 3
}

/**
 * Calculate total alcohol units produced this season across all player stills.
 * Applies character production modifier and coastal bonus (Rum-Runner).
 */
export function calculateSeasonalOutput(
  stills: Distillery[],
  characterClass: string,
  isCoastal: boolean
): number {
  if (stills.length === 0) return 0

  let total = 0
  for (const still of stills) {
    total += getBaseOutput(still.tier)
  }

  // Apply base production modifier (e.g. Vixen -10%)
  let result = applyProductionModifier(characterClass, total)

  // Apply coastal bonus if applicable (e.g. Rum-Runner ×2.0 for coastal home base)
  if (isCoastal) {
    const char = getCharacter(characterClass)
    if (char) result *= char.modifiers.coastalProductionMultiplier
  }

  return Math.floor(result)
}

/**
 * Passive heat generated by all player stills this season.
 */
export function calculatePassiveHeat(stills: Distillery[]): number {
  return stills.reduce((sum, s) => sum + (DISTILLERY_TIERS[s.tier]?.heatPerSeason ?? 0), 0)
}
