-- Seed the 50-city pool
INSERT INTO city_pool (name, state, region, historical_role, primary_alcohol, population_tier, is_coastal, bribe_cost_multiplier) VALUES
  ('Chicago', 'IL', 'Midwest', 'The Outfit HQ (Capone)', 'beer', 'major', 0, 4.0),
  ('New York City', 'NY', 'East Coast', 'Speakeasy Capital', 'gin', 'major', 1, 5.0),
  ('Detroit', 'MI', 'Midwest', 'The Windsor Funnel', 'whiskey', 'major', 1, 3.5),
  ('New Orleans', 'LA', 'South', 'The Wettest City', 'rum', 'large', 1, 2.5),
  ('San Francisco', 'CA', 'West Coast', 'Pacific Import Hub', 'whiskey', 'large', 1, 2.5),
  ('St. Louis', 'MO', 'Midwest', 'Brewing Underground', 'beer', 'large', 0, 2.0),
  ('Miami', 'FL', 'South', 'Rum Row Gateway', 'rum', 'medium', 1, 2.0),
  ('Seattle', 'WA', 'West Coast', 'Puget Sound Smuggling', 'whiskey', 'medium', 1, 2.0),
  ('Galveston', 'TX', 'South', 'The Free State', 'tequila', 'medium', 1, 1.5),
  ('Atlantic City', 'NJ', 'East Coast', 'The Mob''s Playground', 'gin', 'medium', 1, 2.5),
  ('Buffalo', 'NY', 'East Coast', 'Lake Erie Crossing', 'whiskey', 'medium', 1, 1.5),
  ('Mobile', 'AL', 'South', 'Gulf Smuggling', 'rum', 'small', 1, 1.0),
  ('San Diego', 'CA', 'West Coast', 'Tijuana Border Hub', 'tequila', 'medium', 1, 1.5),
  ('Savannah', 'GA', 'South', 'Deep-water Offloading', 'moonshine', 'small', 1, 1.0),
  ('Cleveland', 'OH', 'Midwest', 'Speedboat Alley', 'whiskey', 'large', 1, 2.0),
  ('Duluth', 'MN', 'Midwest', 'North Woods Trade', 'moonshine', 'small', 1, 1.0),
  ('Blackfoot', 'ID', 'West', 'The Constant', 'vodka', 'small', 0, 0.5),
  ('Bristol', 'TN', 'South', 'Moonshine Capital', 'moonshine', 'small', 0, 0.8),
  ('Louisville', 'KY', 'South', 'Medicinal Bourbon', 'bourbon', 'medium', 0, 1.5),
  ('Kansas City', 'MO', 'Midwest', 'Pendergast Machine', 'whiskey', 'large', 0, 2.0),
  ('Chattanooga', 'TN', 'South', 'Appalachian Rail Hub', 'moonshine', 'small', 0, 0.8),
  ('Milwaukee', 'WI', 'Midwest', 'The Great Brewers', 'beer', 'large', 1, 2.0),
  ('Peoria', 'IL', 'Midwest', 'Whiskey Capital', 'whiskey', 'medium', 0, 1.2),
  ('Hot Springs', 'AR', 'South', 'Gangster Neutral Zone', 'bourbon', 'small', 0, 1.0),
  ('Nashville', 'TN', 'South', 'Distribution Center', 'moonshine', 'medium', 0, 1.2),
  ('Des Moines', 'IA', 'Midwest', 'Templeton Rye Hub', 'whiskey', 'medium', 0, 1.0),
  ('Cincinnati', 'OH', 'Midwest', 'King of Bootleggers', 'bourbon', 'large', 0, 1.8),
  ('Pittsburgh', 'PA', 'East Coast', 'Industrial Thirst', 'whiskey', 'large', 0, 1.8),
  ('Atlanta', 'GA', 'South', 'Transport Crossroads', 'moonshine', 'large', 0, 2.0),
  ('Denver', 'CO', 'West', 'Mountain Pass', 'whiskey', 'medium', 0, 1.2),
  ('Omaha', 'NE', 'Midwest', 'The Mini-Chicago', 'beer', 'medium', 0, 1.0),
  ('Salt Lake City', 'UT', 'West', 'High-Desert Transit', 'vodka', 'medium', 0, 1.0),
  ('Albuquerque', 'NM', 'West', 'Southwest Trail', 'tequila', 'small', 0, 0.8),
  ('Memphis', 'TN', 'South', 'Riverboat Smuggling', 'moonshine', 'medium', 0, 1.2),
  ('Indianapolis', 'IN', 'Midwest', 'The Trucker''s Node', 'gin', 'medium', 0, 1.2),
  ('Phoenix', 'AZ', 'West', 'Desert Convoy Stop', 'tequila', 'small', 0, 0.8),
  ('Philadelphia', 'PA', 'East Coast', 'The Clean-up City', 'beer', 'major', 1, 3.5),
  ('Washington DC', 'DC', 'East Coast', 'The Green Hat Hub', 'gin', 'major', 0, 4.0),
  ('Baltimore', 'MD', 'East Coast', 'Defiant Port', 'whiskey', 'large', 1, 2.0),
  ('Los Angeles', 'CA', 'West Coast', 'The Canyons Trade', 'whiskey', 'major', 1, 3.5),
  ('Newark', 'NJ', 'East Coast', 'Zwillman Faction', 'beer', 'medium', 0, 1.5),
  ('Boston', 'MA', 'East Coast', 'Kennedy Territory', 'whiskey', 'large', 1, 2.5),
  ('Minneapolis', 'MN', 'Midwest', 'The Cold Supply', 'moonshine', 'medium', 0, 1.2),
  ('Fort Worth', 'TX', 'South', 'Hell''s Half Acre', 'bourbon', 'medium', 0, 1.2),
  ('Portland', 'OR', 'West Coast', 'Shanghai Tunnels', 'whiskey', 'medium', 1, 1.5),
  ('Oklahoma City', 'OK', 'South', 'The Strictly Dry Hub', 'moonshine', 'medium', 0, 1.0),
  ('Little Rock', 'AR', 'South', 'Political Fixers', 'bourbon', 'small', 0, 0.8),
  ('Richmond', 'VA', 'East Coast', 'Piedmont Still Hub', 'moonshine', 'medium', 0, 1.2),
  ('Providence', 'RI', 'East Coast', 'The Tiny Rebel', 'rum', 'small', 1, 1.0),
  ('Las Vegas', 'NV', 'West', 'The Vice Frontier', 'gin', 'small', 0, 1.0);
